version: '3'
services:
    springboot-app:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      volumes:
        - ./target/example-0.0.1-SNAPSHOT.jar:/app